
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("73524ac0-a3f6-4a81-9ca9-ae99b243814e")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("SIGTModel", "FK_OrdenServicio_Clientes1", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Clientes), "OrdenServicio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrdenServicio), True)>
<Assembly: EdmRelationshipAttribute("SIGTModel", "FK_Reparaciones_OrdenServicio", "OrdenServicio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(OrdenServicio), "Reparaciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Reparaciones), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class SIGTEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Inicializa un nuevo objeto SIGTEntities usando la cadena de conexión encontrada en la sección 'SIGTEntities' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SIGTEntities", "SIGTEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto SIGTEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SIGTEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto SIGTEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SIGTEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Clientes() As ObjectSet(Of Clientes)
        Get
            If (_Clientes Is Nothing) Then
                _Clientes = MyBase.CreateObjectSet(Of Clientes)("Clientes")
            End If
            Return _Clientes
        End Get
    End Property

    Private _Clientes As ObjectSet(Of Clientes)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property OrdenServicio() As ObjectSet(Of OrdenServicio)
        Get
            If (_OrdenServicio Is Nothing) Then
                _OrdenServicio = MyBase.CreateObjectSet(Of OrdenServicio)("OrdenServicio")
            End If
            Return _OrdenServicio
        End Get
    End Property

    Private _OrdenServicio As ObjectSet(Of OrdenServicio)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Reparaciones() As ObjectSet(Of Reparaciones)
        Get
            If (_Reparaciones Is Nothing) Then
                _Reparaciones = MyBase.CreateObjectSet(Of Reparaciones)("Reparaciones")
            End If
            Return _Reparaciones
        End Get
    End Property

    Private _Reparaciones As ObjectSet(Of Reparaciones)

    #End Region
    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToClientes(ByVal clientes As Clientes)
        MyBase.AddObject("Clientes", clientes)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet OrdenServicio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToOrdenServicio(ByVal ordenServicio As OrdenServicio)
        MyBase.AddObject("OrdenServicio", ordenServicio)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Reparaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToReparaciones(ByVal reparaciones As Reparaciones)
        MyBase.AddObject("Reparaciones", reparaciones)
    End Sub

    #End Region
End Class

#End Region
#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SIGTModel", Name:="Clientes")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Clientes
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Clientes.
    ''' </summary>
    ''' <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
    Public Shared Function CreateClientes(iDCliente As Global.System.Int32) As Clientes
        Dim clientes as Clientes = New Clientes
        clientes.IDCliente = iDCliente
        Return clientes
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RazonSocial() As Global.System.String
        Get
            Return _RazonSocial
        End Get
        Set
            OnRazonSocialChanging(value)
            ReportPropertyChanging("RazonSocial")
            _RazonSocial = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RazonSocial")
            OnRazonSocialChanged()
        End Set
    End Property

    Private _RazonSocial As Global.System.String
    Private Partial Sub OnRazonSocialChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRazonSocialChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DVH() As Global.System.String
        Get
            Return _DVH
        End Get
        Set
            OnDVHChanging(value)
            ReportPropertyChanging("DVH")
            _DVH = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DVH")
            OnDVHChanged()
        End Set
    End Property

    Private _DVH As Global.System.String
    Private Partial Sub OnDVHChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDVHChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDEstado() As Nullable(Of Global.System.Int32)
        Get
            Return _IDEstado
        End Get
        Set
            OnIDEstadoChanging(value)
            ReportPropertyChanging("IDEstado")
            _IDEstado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDEstado")
            OnIDEstadoChanged()
        End Set
    End Property

    Private _IDEstado As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDEstadoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDEstadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDCliente() As Global.System.Int32
        Get
            Return _IDCliente
        End Get
        Set
            If (_IDCliente <> Value) Then
                OnIDClienteChanging(value)
                ReportPropertyChanging("IDCliente")
                _IDCliente = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDCliente")
                OnIDClienteChanged()
            End If
        End Set
    End Property

    Private _IDCliente As Global.System.Int32
    Private Partial Sub OnIDClienteChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDClienteChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastEditDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastEditDate
        End Get
        Set
            OnLastEditDateChanging(value)
            ReportPropertyChanging("LastEditDate")
            _LastEditDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastEditDate")
            OnLastEditDateChanged()
        End Set
    End Property

    Private _LastEditDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastEditDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastEditDateChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreationDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreationDate
        End Get
        Set
            OnCreationDateChanging(value)
            ReportPropertyChanging("CreationDate")
            _CreationDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreationDate")
            OnCreationDateChanged()
        End Set
    End Property

    Private _CreationDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreationDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreationDateChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SIGTModel", "FK_OrdenServicio_Clientes1", "OrdenServicio")>
     Public Property OrdenServicio() As EntityCollection(Of OrdenServicio)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrdenServicio)("SIGTModel.FK_OrdenServicio_Clientes1", "OrdenServicio")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrdenServicio)("SIGTModel.FK_OrdenServicio_Clientes1", "OrdenServicio", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SIGTModel", Name:="OrdenServicio")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OrdenServicio
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto OrdenServicio.
    ''' </summary>
    ''' <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
    ''' <param name="iDOrden">Valor inicial de la propiedad IDOrden.</param>
    Public Shared Function CreateOrdenServicio(iDCliente As Global.System.Int32, iDOrden As Global.System.Int32) As OrdenServicio
        Dim ordenServicio as OrdenServicio = New OrdenServicio
        ordenServicio.IDCliente = iDCliente
        ordenServicio.IDOrden = iDOrden
        Return ordenServicio
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDCliente() As Global.System.Int32
        Get
            Return _IDCliente
        End Get
        Set
            OnIDClienteChanging(value)
            ReportPropertyChanging("IDCliente")
            _IDCliente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDCliente")
            OnIDClienteChanged()
        End Set
    End Property

    Private _IDCliente As Global.System.Int32
    Private Partial Sub OnIDClienteChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDClienteChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FechaIngreso() As Global.System.String
        Get
            Return _FechaIngreso
        End Get
        Set
            OnFechaIngresoChanging(value)
            ReportPropertyChanging("FechaIngreso")
            _FechaIngreso = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FechaIngreso")
            OnFechaIngresoChanged()
        End Set
    End Property

    Private _FechaIngreso As Global.System.String
    Private Partial Sub OnFechaIngresoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFechaIngresoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Numero() As Global.System.String
        Get
            Return _Numero
        End Get
        Set
            OnNumeroChanging(value)
            ReportPropertyChanging("Numero")
            _Numero = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Numero")
            OnNumeroChanged()
        End Set
    End Property

    Private _Numero As Global.System.String
    Private Partial Sub OnNumeroChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNumeroChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDOrden() As Global.System.Int32
        Get
            Return _IDOrden
        End Get
        Set
            If (_IDOrden <> Value) Then
                OnIDOrdenChanging(value)
                ReportPropertyChanging("IDOrden")
                _IDOrden = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDOrden")
                OnIDOrdenChanged()
            End If
        End Set
    End Property

    Private _IDOrden As Global.System.Int32
    Private Partial Sub OnIDOrdenChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDOrdenChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastEditDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastEditDate
        End Get
        Set
            OnLastEditDateChanging(value)
            ReportPropertyChanging("LastEditDate")
            _LastEditDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastEditDate")
            OnLastEditDateChanged()
        End Set
    End Property

    Private _LastEditDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastEditDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastEditDateChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreationDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreationDate
        End Get
        Set
            OnCreationDateChanging(value)
            ReportPropertyChanging("CreationDate")
            _CreationDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreationDate")
            OnCreationDateChanged()
        End Set
    End Property

    Private _CreationDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreationDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreationDateChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SIGTModel", "FK_OrdenServicio_Clientes1", "Clientes")>
    Public Property Clientes() As Clientes
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SIGTModel.FK_OrdenServicio_Clientes1", "Clientes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SIGTModel.FK_OrdenServicio_Clientes1", "Clientes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ClientesReference() As EntityReference(Of Clientes)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Clientes)("SIGTModel.FK_OrdenServicio_Clientes1", "Clientes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Clientes)("SIGTModel.FK_OrdenServicio_Clientes1", "Clientes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SIGTModel", "FK_Reparaciones_OrdenServicio", "Reparaciones")>
     Public Property Reparaciones() As EntityCollection(Of Reparaciones)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Reparaciones)("SIGTModel.FK_Reparaciones_OrdenServicio", "Reparaciones")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Reparaciones)("SIGTModel.FK_Reparaciones_OrdenServicio", "Reparaciones", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SIGTModel", Name:="Reparaciones")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Reparaciones
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Reparaciones.
    ''' </summary>
    ''' <param name="iDReparacion">Valor inicial de la propiedad IDReparacion.</param>
    ''' <param name="iDOrden">Valor inicial de la propiedad IDOrden.</param>
    Public Shared Function CreateReparaciones(iDReparacion As Global.System.Int32, iDOrden As Global.System.Int32) As Reparaciones
        Dim reparaciones as Reparaciones = New Reparaciones
        reparaciones.IDReparacion = iDReparacion
        reparaciones.IDOrden = iDOrden
        Return reparaciones
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDReparacion() As Global.System.Int32
        Get
            Return _IDReparacion
        End Get
        Set
            If (_IDReparacion <> Value) Then
                OnIDReparacionChanging(value)
                ReportPropertyChanging("IDReparacion")
                _IDReparacion = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDReparacion")
                OnIDReparacionChanged()
            End If
        End Set
    End Property

    Private _IDReparacion As Global.System.Int32
    Private Partial Sub OnIDReparacionChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDReparacionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDOrden() As Global.System.Int32
        Get
            Return _IDOrden
        End Get
        Set
            OnIDOrdenChanging(value)
            ReportPropertyChanging("IDOrden")
            _IDOrden = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDOrden")
            OnIDOrdenChanged()
        End Set
    End Property

    Private _IDOrden As Global.System.Int32
    Private Partial Sub OnIDOrdenChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDOrdenChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Serie() As Global.System.String
        Get
            Return _Serie
        End Get
        Set
            OnSerieChanging(value)
            ReportPropertyChanging("Serie")
            _Serie = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Serie")
            OnSerieChanged()
        End Set
    End Property

    Private _Serie As Global.System.String
    Private Partial Sub OnSerieChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSerieChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDEstado() As Nullable(Of Global.System.Int32)
        Get
            Return _IDEstado
        End Get
        Set
            OnIDEstadoChanging(value)
            ReportPropertyChanging("IDEstado")
            _IDEstado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDEstado")
            OnIDEstadoChanged()
        End Set
    End Property

    Private _IDEstado As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDEstadoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDEstadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDEquipo() As Nullable(Of Global.System.Int32)
        Get
            Return _IDEquipo
        End Get
        Set
            OnIDEquipoChanging(value)
            ReportPropertyChanging("IDEquipo")
            _IDEquipo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDEquipo")
            OnIDEquipoChanged()
        End Set
    End Property

    Private _IDEquipo As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDEquipoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDEquipoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDUsuario() As Nullable(Of Global.System.Int32)
        Get
            Return _IDUsuario
        End Get
        Set
            OnIDUsuarioChanging(value)
            ReportPropertyChanging("IDUsuario")
            _IDUsuario = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDUsuario")
            OnIDUsuarioChanged()
        End Set
    End Property

    Private _IDUsuario As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDUsuarioChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDUsuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DVH() As Nullable(Of Global.System.Int32)
        Get
            Return _DVH
        End Get
        Set
            OnDVHChanging(value)
            ReportPropertyChanging("DVH")
            _DVH = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DVH")
            OnDVHChanged()
        End Set
    End Property

    Private _DVH As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDVHChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDVHChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Falla() As Global.System.String
        Get
            Return _Falla
        End Get
        Set
            OnFallaChanging(value)
            ReportPropertyChanging("Falla")
            _Falla = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Falla")
            OnFallaChanged()
        End Set
    End Property

    Private _Falla As Global.System.String
    Private Partial Sub OnFallaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFallaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Tarea() As Global.System.String
        Get
            Return _Tarea
        End Get
        Set
            OnTareaChanging(value)
            ReportPropertyChanging("Tarea")
            _Tarea = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Tarea")
            OnTareaChanged()
        End Set
    End Property

    Private _Tarea As Global.System.String
    Private Partial Sub OnTareaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTareaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Observaciones() As Global.System.String
        Get
            Return _Observaciones
        End Get
        Set
            OnObservacionesChanging(value)
            ReportPropertyChanging("Observaciones")
            _Observaciones = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Observaciones")
            OnObservacionesChanged()
        End Set
    End Property

    Private _Observaciones As Global.System.String
    Private Partial Sub OnObservacionesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnObservacionesChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FechaReparacion() As Global.System.String
        Get
            Return _FechaReparacion
        End Get
        Set
            OnFechaReparacionChanging(value)
            ReportPropertyChanging("FechaReparacion")
            _FechaReparacion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FechaReparacion")
            OnFechaReparacionChanged()
        End Set
    End Property

    Private _FechaReparacion As Global.System.String
    Private Partial Sub OnFechaReparacionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFechaReparacionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Modelo() As Global.System.String
        Get
            Return _Modelo
        End Get
        Set
            OnModeloChanging(value)
            ReportPropertyChanging("Modelo")
            _Modelo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Modelo")
            OnModeloChanged()
        End Set
    End Property

    Private _Modelo As Global.System.String
    Private Partial Sub OnModeloChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModeloChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastEditDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastEditDate
        End Get
        Set
            OnLastEditDateChanging(value)
            ReportPropertyChanging("LastEditDate")
            _LastEditDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastEditDate")
            OnLastEditDateChanged()
        End Set
    End Property

    Private _LastEditDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastEditDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastEditDateChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreationDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreationDate
        End Get
        Set
            OnCreationDateChanging(value)
            ReportPropertyChanging("CreationDate")
            _CreationDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreationDate")
            OnCreationDateChanged()
        End Set
    End Property

    Private _CreationDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreationDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreationDateChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SIGTModel", "FK_Reparaciones_OrdenServicio", "OrdenServicio")>
    Public Property OrdenServicio() As OrdenServicio
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrdenServicio)("SIGTModel.FK_Reparaciones_OrdenServicio", "OrdenServicio").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrdenServicio)("SIGTModel.FK_Reparaciones_OrdenServicio", "OrdenServicio").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OrdenServicioReference() As EntityReference(Of OrdenServicio)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrdenServicio)("SIGTModel.FK_Reparaciones_OrdenServicio", "OrdenServicio")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrdenServicio)("SIGTModel.FK_Reparaciones_OrdenServicio", "OrdenServicio", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

